coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false

ignore:
  - 'src/**/*.test.ts'
  - 'src/index.ts'
  - 'src/features/**'
  - 'dist'
  - 'example'
